#!/bin/bash

# The basename of our binary
BASE="cpmulator"

# I don't even ..
go env -w GOFLAGS="-buildvcs=false"

# Disable fatal error on workers
if [ -d /github/workspace ] ; then
    git config --global --add safe.directory /github/workspace
fi

#
# We build for many platforms.
#
BUILD_PLATFORMS="linux darwin freebsd openbsd netbsd windows"
BUILD_ARCHS="amd64 386"

# For each platform
for OS in ${BUILD_PLATFORMS[@]}; do

    # For each arch
    for ARCH in ${BUILD_ARCHS[@]}; do

        # Setup a suffix for the binary
        SUFFIX="${OS}"

        # i386 is better than 386
        if [ "$ARCH" = "386" ]; then
            SUFFIX="${SUFFIX}-i386"
        else
            SUFFIX="${SUFFIX}-${ARCH}"
        fi

        # Windows binaries should end in .EXE
        if [ "$OS" = "windows" ]; then
            SUFFIX="${SUFFIX}.exe"
        fi

        echo "Building for ${OS} [${ARCH}] -> ${BASE}-${SUFFIX}"

        # Run the build
        export GOARCH=${ARCH}
        export GOOS=${OS}
        export CGO_ENABLED=0

        go build -ldflags "-X github.com/skx/cpmulator/version.version=$(git describe --tags)" -o "${BASE}-${SUFFIX}"

    done
done
